#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run typecheck
npm run check

npm run test:run
# npm run test:e2e

# npm run build

git fetch origin
git merge --no-commit --no-ff origin/main
git reset --hard HEAD