@protocol = http
@hostname = localhost
@port = 5173
@host = {{protocol}}://{{hostname}}:{{port}}

// MOTE: num run dev -- --host

###
GET {{host}}

###
GET {{host}}/api/get-translation/Hi/en-US/ja-JP

###
POST {{host}}/api/log
Content-Type: application/json

{
	"level": { "value": "info" },
	"message": "Hello World"
}

###
POST {{host}}/api/log
Content-Type: application/json

{
	"level": { "value": "info2" },
	"message": "Hello World"
}
